(function(root){
  'use strict';
  const D=root.NextMusicData;
  const h=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const phaseOptions=phase=>Object.entries(D.phases).map(([key,label])=>`<option value="${key}" ${key===phase?'selected':''}>${label}</option>`).join('');
  function printHTML(S,meta={}){
    const tracks=D.ordered(S),columns=tracks.length>12;
    return `<section class="music-print-page"><header class="music-sheet-header"><span>NEXT · MUSIKBILAG</span><h2>Dit musikvalg · ${h(S.music)}</h2><p>${h(meta.title||'Træningsprogram')}${meta.client?' · '+h(meta.client):''}${meta.date?' · '+h(meta.date):''}</p></header><div class="music-phase-summary">${Object.entries(D.phases).map(([key,label])=>`<span><b>${label}</b> ${D.minutes(S,key)} min</span>`).join('')}</div><p class="music-sheet-help">Klik på en titel for at finde nummeret på Spotify. Brug programmets arbejdstider og skift musik ved blokskift.</p>${tracks.length?`<ol class="music-print-list ${columns?'two-columns':''}" style="--music-rows:${Math.ceil(tracks.length/2)}">${tracks.map((t,i)=>`<li class="music-print-row"><b>${String(i+1).padStart(2,'0')}</b><div><a href="${h(D.href(t))}" target="_blank" rel="noopener noreferrer">${h(t.title)} ↗</a><span>${h(t.artist)}</span><small>${D.phases[t.phase]}</small></div></li>`).join('')}</ol>`:'<p>Ingen numre valgt. Vælg musik i generatoren før næste eksport.</p>'}<footer class="music-sheet-footer">${tracks.length} valgte numre · Spotify-links søger på titel og kunstner. Numrene starter, når du vælger afspilning på Spotify.</footer></section>`;
  }
  function render(){
    const A=root.NEXTPlanner;if(!A)return;const S=A.state,target=document.getElementById('music-plan');if(!target)return;
    const picked=D.selection(S),tracks=D.catalog[S.music];
    document.getElementById('spotify-main').href='https://open.spotify.com/search/'+encodeURIComponent(S.music+' workout');
    target.innerHTML=`<div class="music-browser"><div class="music-browser-head"><div><span class="pro-kicker">20 MUSIKFORSLAG</span><h3>${h(S.music)}</h3></div><label><span>Musiksmag</span><select id="music-genre-picker">${Object.keys(D.catalog).map(g=>`<option ${g===S.music?'selected':''}>${h(g)}</option>`).join('')}</select></label></div><p class="music-help">Vælg numre med +. Spotify-linket søger på titel og kunstner, så du kan lytte og vælge version.</p><div class="music-actions"><button type="button" data-music-action="all">Vælg alle 20</button><button type="button" data-music-action="defaults">Brug startforslag</button><button type="button" data-music-action="clear">Ryd valg</button><strong role="status">${picked.length} af 20 valgt</strong></div><div class="music-track-grid">${tracks.map((t,i)=>{const checked=picked.some(x=>x.id===t.id);return `<article class="music-track ${checked?'is-picked':''}"><button type="button" class="music-pick" data-music-action="toggle" data-track="${t.id}" aria-pressed="${checked}" aria-label="${checked?'Fravælg':'Vælg'} ${h(t.title)}">${checked?'✓':'+'}</button><div><span class="music-track-number">${String(i+1).padStart(2,'0')} · Forslag til ${D.phases[t.phase].toLowerCase()}</span><h4>${h(t.title)}</h4><p>${h(t.artist)}</p><a href="${h(D.href(t))}" target="_blank" rel="noopener noreferrer" aria-label="Find ${h(t.title)} af ${h(t.artist)} på Spotify">Spotify ↗</a></div></article>`;}).join('')}</div></div><div class="music-selection"><div class="music-selection-title"><span class="pro-kicker">MED I DIN PDF</span><h3>Dit musikvalg</h3><p>Flyt numre mellem træningens dele, og vælg rækkefølgen med pilene. Dit valg gemmes sammen med programmet.</p></div>${Object.entries(D.phases).map(([phase,label])=>{const rows=D.selected(S).filter(t=>t.phase===phase);return `<section class="music-selected-phase"><header><h4>${label}</h4><span>${D.minutes(S,phase)} min i programmet</span></header>${rows.length?`<ol>${rows.map((t,i)=>`<li><div class="music-selected-copy"><a href="${h(D.href(t))}" target="_blank" rel="noopener noreferrer">${h(t.title)} ↗</a><small>${h(t.artist)}</small></div><label class="music-phase-select"><span class="visually-hidden">Placér ${h(t.title)}</span><select data-music-phase="${t.id}" aria-label="Placér ${h(t.title)}">${phaseOptions(t.phase)}</select></label><div class="music-row-buttons"><button type="button" data-music-action="up" data-track="${t.id}" aria-label="Flyt ${h(t.title)} op" ${i===0?'disabled':''}>↑</button><button type="button" data-music-action="down" data-track="${t.id}" aria-label="Flyt ${h(t.title)} ned" ${i===rows.length-1?'disabled':''}>↓</button><button type="button" data-music-action="toggle" data-track="${t.id}" aria-label="Fjern ${h(t.title)}">×</button></div></li>`).join('')}</ol>`:'<p class="music-empty">Ingen numre valgt til denne del.</p>'}</section>`;}).join('')}</div>`;
    target.onclick=event=>{const button=event.target.closest('[data-music-action]');if(!button)return;const action=button.dataset.musicAction,id=button.dataset.track;root.NextPro?.remember();let chosen=D.selection(S);
      if(action==='all')S.musicSelections[S.music]=tracks.map(t=>({id:t.id,phase:t.phase}));
      else if(action==='defaults')S.musicSelections[S.music]=D.defaults(S.music);
      else if(action==='clear')S.musicSelections[S.music]=[];
      else if(action==='toggle'){const pos=chosen.findIndex(x=>x.id===id);if(pos>=0)chosen.splice(pos,1);else{const t=tracks.find(t=>t.id===id);if(t)chosen.push({id:t.id,phase:t.phase});}}
      else if(action==='up'||action==='down'){const pos=chosen.findIndex(x=>x.id===id);if(pos<0)return;const same=chosen.map((x,i)=>({x,i})).filter(v=>v.x.phase===chosen[pos].phase);const at=same.findIndex(v=>v.i===pos),other=same[at+(action==='up'?-1:1)];if(other)[chosen[pos],chosen[other.i]]=[chosen[other.i],chosen[pos]];}
      render();A.markUnsaved();const focus=Array.from(target.querySelectorAll('[data-music-action]')).find(el=>el.dataset.musicAction===action&&el.dataset.track===id);focus?.focus({preventScroll:true});
    };
    target.onchange=event=>{if(event.target.id==='music-genre-picker'){root.NextPro?.remember();S.music=event.target.value;document.getElementById('music').value=S.music;}else if(event.target.dataset.musicPhase){root.NextPro?.remember();const row=D.selection(S).find(x=>x.id===event.target.dataset.musicPhase);if(row&&D.phases[event.target.value])row.phase=event.target.value;}else return;render();A.markUnsaved();};
    const sheet=document.getElementById('print-music-sheet');sheet.innerHTML=printHTML(S,root.NextPro?.musicMeta?.()||{});
    // Keep the music sheet after the customer exercises in the real print DOM.
    const pages=document.getElementById('print-exercise-pages');if(pages)pages.after(sheet);
  }
  root.NextMusic={render,printHTML};
}(window));
